# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: add {{ DEPLOY_HOST }} to .ssh/known_hosts
          command: ssh-keyscan -H {{ DEPLOY_HOST }} >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - {{ FINGERPRINTS }}
      - run: sudo apt install -y rsync
        # specify any bash command here prefixed with `run: `
        # - run: go get -v -t -d ./...
        # - run: go test -v ./...
      - run: go get -v github.com/gohugoio/hugo
      - deploy:
          command: ./deploy
